### ISSUE TITLE
Porting the "Orange Hawaiian" outfit from SR

### ISSUE THREAD

**Issue by JohnWestJones** [hrzntal/horizon#1001]
### Type of Request

Addition

### About the Request

Hey, just asking if it's possible to have it on this server as well. 

### Why should this Idea be considered

It's a nice outfit, and I personally enjoy it immensely with my detective.

**Comment by Azarak** [comment]
Should anyone take it up, consider porting every hawaiian outfit that you can find, especially the iconic blue-ish ones
