### ISSUE TITLE
Cargo boxes can spawn inside shuttle window in Kilo

### ISSUE THREAD

**Issue by Dr-0range** [hrzntal/horizon#113]
## Reproduction:
For whatever reason cargo boxes can spawn in the back windows 
![unknown](https://user-images.githubusercontent.com/61362684/106676036-79fcdc80-65b6-11eb-9c55-9b21a0529c0a.png)

**Comment by I6NIS** [comment]
Looks like Icebox has the same issue 
![image](https://user-images.githubusercontent.com/13191065/107123846-4533a280-68a0-11eb-8bb1-89d3f9a64b22.png)

**Comment by Dr-0range** [comment]
Also an issue in Ice box station it seems.

**Comment by atakiya** [comment]
Closing as stale, no new reports have been done so far and I couldn't reproduce this issue either anymore.
Might have been fixed with an upstream patch at some point.
