### ISSUE TITLE
Request: Ghost Cafe / Testing Area

### ISSUE THREAD

**Issue by Owai-Seek** [hrzntal/horizon#114]
Not sure if this would require modular mapping first, but it would be a huge boon to be able to spawn in a ghost cafe (which for now, could just be the Ninja Lockdown area.) To perform simple tests. A quick spawn in, test, and cryo, so checking something simple doesn't feel too awkward.

**Comment by Azarak** [comment]
Test area is a localhost, there shouldnt be any in-round testing area for a production server, for any performance issues and maintenance costs it could take

**Comment by Owai-Seek** [comment]
I've used it before on Citadel to test some basic stuff as a player without having to boot up my own localhost, which was a really nice convince factor when looking up bugs other people have mentioned to me. (One of the examples being, certain sprites not showing up for botany items, specific food items being invisible, ect.) It's not strictly necessary, but it can be helpful.

**Comment by Avunia** [comment]
Sorry but no, there's little reason to maintain a separate test area just for this kind of stuff.

People already have freedom to cryo in/out how they want (given it's not being abused for reasons).
Testing is also not good to do on the live server as bugs could be fixed on the edge branch while the live server is still running a round that is behind in the commit history.
Or something was changed at runtime by staff, or configurations are broken, etc.

There's tons of reasons to not test on production.
