### ISSUE TITLE
Add Pubby Chef Ordering Console.

### ISSUE THREAD

**Issue by CypressBz** [hrzntal/horizon#1170]
### Type of Request

Addition

### About the Request

Pubby doesn't have the thing to make up for a poorly staffed botany, thus making chef a harder job.
The ordering console also has some stuff you otherwise can't get.

### Why should this Idea be considered

I heard some folks complaining about this, that's all.

**Comment by KathrinBailey** [comment]
I'm gonna try and touch up Pubby service, I'll add it on that PR.

**Comment by MissFox0810** [comment]
Taking over to quick fix
