### ISSUE TITLE
Fireman carry targets remain standing up when dropped

### ISSUE THREAD

**Issue by Dr-0range** [hrzntal/horizon#126]
## Reproduction:
Dropping someone incapacitated (or dead) while carrying makes them remain standing up, they can also no longer be knocked down again afterwards. Even removing limbs doesn't knock them down.
![image](https://user-images.githubusercontent.com/61362684/107540265-26961a00-6bc6-11eb-884b-49aa9f2f2fe3.png)
![image](https://user-images.githubusercontent.com/61362684/107540842-cbb0f280-6bc6-11eb-9761-2c75c509704a.png)
![image](https://user-images.githubusercontent.com/61362684/107541256-395d1e80-6bc7-11eb-9959-2f9bc1dc4ccf.png)

**Comment by FlamingLily** [comment]
This is a very old bug, and has something to do with the setting of resting state when fireman carrying. Unfortunately, reproducing it is not as easy as just fireman carrying any old person

**Comment by FlamingLily** [comment]
As a "bandaid" players who are dead or unconscious can re-set themself to resting, and it will lie them down properly, and often even fix future fireman carryings.

**Comment by atakiya** [comment]
It might be an oversight with the auto-stand up.
A feature that isn't really desirable *here* either way, maybe removal of it will fix it.
I'll definitely have a look at some point though.

**Comment by Azarak** [comment]
No longer the case
