### ISSUE TITLE
Griffon Head hat deletes several lizard parts and shows as invisible.

### ISSUE THREAD

**Issue by Owai-Seek** [hrzntal/horizon#128]
## Reproduction:

Plop it on.

Character Settings:
![image](https://user-images.githubusercontent.com/7543955/107749446-9c92a200-6ce8-11eb-9046-414433780e30.png)

## Screenshots:

![dreamseeker_2SIM8pZNTh](https://user-images.githubusercontent.com/7543955/107749292-58070680-6ce8-11eb-9266-6d5bdeb517ad.png)
![dreamseeker_xkmTL154I9](https://user-images.githubusercontent.com/7543955/107749302-5b9a8d80-6ce8-11eb-91f1-384357482045.png)
![image](https://user-images.githubusercontent.com/7543955/107749523-bdf38e00-6ce8-11eb-9633-e09f3fd7bdf5.png)

**Comment by Azarak** [comment]
Should be already fixed
