### ISSUE TITLE
You can step on (and trip over) objects when two-handing push broom, if not wearing shoes.

### ISSUE THREAD

**Issue by Owai-Seek** [hrzntal/horizon#131]
## Reproduction:

Not sure how you want to treat upstream issues, so here's the issue I posted there as well.

https://github.com/tgstation/tgstation/issues/55567

![dreamseeker_Jq5yy3GWJc](https://user-images.githubusercontent.com/7543955/107750790-7ff76980-6cea-11eb-8293-b90d51c93f71.png)
![dreamseeker_1sOPMmpuMO](https://user-images.githubusercontent.com/7543955/107750801-82f25a00-6cea-11eb-8cc6-ff0cb070f953.png)

**Comment by Owai-Seek** [comment]
Seems this was fixed over on TG, but we don't have a mirror function yet.

https://github.com/tgstation/tgstation/pull/57105

**Comment by FlamingLily** [comment]
This is fixed! One of the TG syncs must've done it

**Comment by atakiya** [comment]
Oh yeah our rebase in April/May fast forwarded us beyond this. Thanks for the heads up!
