### ISSUE TITLE
Wheely Shoes are wonky with digi feet.

### ISSUE THREAD

**Issue by Owai-Seek** [hrzntal/horizon#133]
## Reproduction:

`/obj/item/clothing/shoes/wheelys`
Show up below and to the left of the character sprite. The other two are invisible, so, a much more minor issue for those.

![image](https://user-images.githubusercontent.com/7543955/107751890-f9438c00-6ceb-11eb-86eb-9a33ae4547dc.png)

**Comment by Azarak** [comment]
Fixed
