### ISSUE TITLE
Cannot wash faces in sinks.

### ISSUE THREAD

**Issue by Owai-Seek** [hrzntal/horizon#134]
## Reproduction:

(Probably Upstream)
https://github.com/tgstation/tgstation/issues/55649

![image](https://user-images.githubusercontent.com/7543955/107752234-740ca700-6cec-11eb-893f-4159dfb9c6b6.png)
![image](https://user-images.githubusercontent.com/7543955/107752263-7cfd7880-6cec-11eb-9714-e9340cea7150.png)

**Comment by atakiya** [comment]
Was upstream, works now.
