### ISSUE TITLE
Grillable component turns meat slabs into unedible steaks

### ISSUE THREAD

**Issue by atakiya** [hrzntal/horizon#262]
## Reproduction:
- Have a slab of monkey / plain meat (typepath `/meat/slab`)
- Put on grill (or griddle, untested)
- Let it grill until it displays a message (adds the component code wise)
- Resulting piece of steak cannot be consumed

Pretty sure this is an upstream issue.
Priority low as this will be replaced by what #42 entails.

**Comment by Owai-Seek** [comment]
Found several upstream mentions of this issue, I think it originates from here: https://github.com/tgstation/tgstation/issues/59423

- Thermally Processed Meat Product cannot be eaten. (Meat Product cooked on a griddle.)
- Meat products from butchered monkeys cannot be eaten. This includes Meat Slabs, Cutlets, Bacon, but not Meatballs, for some reason.

As you said though, might not be relevant soon.

**Comment by atakiya** [comment]
Will be fixed when tgstation/tgstation#59855 gets mirrored.

**Comment by atakiya** [comment]
Sort of fixed. Further fixes will be done with the removal later on. 😄
