### ISSUE TITLE
Lift/Elevator Controller

### ISSUE THREAD

**Issue by atakiya** [hrzntal/horizon#334]
## About The Feature Request
Proper control interface for elevators.

Contains
- Button panel
- Call buttons
- Ability to move to floors by called stack (FIFO)
- Internal and External Door (NTnet?) I/O
- Velocity (no instant-teleport)

Optional
- Alert mode
- Notifications/Status displays
- Music?

**Comment by Azarak** [comment]
I'll attempt coding those in

**Comment by atakiya** [comment]
This was implemented by #434
