### ISSUE TITLE
Explosions on ruin generated tiles produce non planetary results.

### ISSUE THREAD

**Issue by CypressBz** [hrzntal/horizon#343]
## Reproduction:
Generating a large explosion on `turf/closed/mineral/random/jungle` removes the planetary stone turf, and replaces indestructible plating turfs in it's place.

![image](https://user-images.githubusercontent.com/7775562/124202853-f8e03d80-daa0-11eb-98b2-22f1c30fe352.png)

**Comment by Azarak** [comment]
You've used `/turf/closed/mineral` Which has baseturfs of airless asteroid sand, then airless plating, then level baseturf. This is not a bug just bad usage of that type in planetary levels. `/turf/closed/mineral` is designed for space levels, however, it doesn't make sense that it goes from sand to plating, so I'll fix that

**Comment by atakiya** [comment]
Closing as stale. Reopen if issue persists.
