### ISSUE TITLE
Bearcat Cargo Dock's tiny fans are missplaced by one tile

### ISSUE THREAD

**Issue by rhodochrositech** [hrzntal/horizon#349]
On the map Bearcat, there is a small error where the fans on the cargo dock spawn one tile behind, leaving a lethal zone of vaccum that is unfixable. This image demonstrates a simple and easy fix. Thank you!

![image](https://user-images.githubusercontent.com/86504079/124334243-7ae56a80-db64-11eb-96ef-8fd0a5d849ad.png)

**Comment by Owai-Seek** [comment]
I -believe- this was fixed with https://github.com/hrzntal/horizon/pull/362/ ?

**Comment by atakiya** [comment]
Reopen if issue persists.
