### ISSUE TITLE
Action buttons unreliable

### ISSUE THREAD

**Issue by atakiya** [hrzntal/horizon#350]
Reporting client version: 514.1557
Reporting client version: 514.1556

## Round ID:
85

## Reproduction:
Attempt to use any action buttons (top right), like PDA light, BST return.
Will not work reliably, or at all.
~~This only happens on the FTV Bearcat (`tradership.dmm`)~~
Found to be happening on the FTV Bearcat AND tramstation.

**Comment by Azarak** [comment]
Did you happen to pass by the directional firelocks? I noticed some very strange things about them

**Comment by atakiya** [comment]
> Did you happen to pass by the directional firelocks? I noticed some very strange things about them

I think I did before.
However I just tested it on the live server on tramstation (Round 91) and it still occurs when using BST return, without passing by any firelocks.

**Comment by Azarak** [comment]
That's concerning. Did it ever happen outside of being a BST?

**Comment by atakiya** [comment]
> That's concerning. Did it ever happen outside of being a BST?

Yes it happens all the time.
I found a way to avoid it though, it seems to be somehting with the icon layer.

Take the following image
![image](https://user-images.githubusercontent.com/6952402/124443536-0c7bf480-dd7e-11eb-955e-9f4e96a18b91.png)

Clicking the VERY border, works fine. Anywhere inside, it requires me to SPAM click it, and will even lock up my client in some cases until it processes everything.
![image](https://user-images.githubusercontent.com/6952402/124444642-1e11cc00-dd7f-11eb-8921-ebffdee7175c.png)

**Comment by Azarak** [comment]
Something with emissive overlays maybe, I dont recall much else being changed regarding icons of all sorts of stuff, or UI

**Comment by atakiya** [comment]
Will check stable BYOND branch.
Oddly enough, I seem to be the only one wtih the issue, despite using the same version as other people now (1556)

**Comment by atakiya** [comment]
Closing, this is a thirdparty issue on my end due to a (yet unknown) window layering above the exact area.

![image](https://user-images.githubusercontent.com/6952402/129457578-1112bc65-6618-4c74-842b-f78222320c25.png)
