### ISSUE TITLE
Overhaul ghetto surgery

### ISSUE THREAD

**Issue by atakiya** [hrzntal/horizon#385]
## About The Feature Request
Check and overhaul tools for ghetto surgery.
Bonesetting could use a `wrench`, currently only `bone gel` & `tape` are alternatives, for example.

## Why It's Good For The Game
More ways to fix something on the go.

**Comment by Azarak** [comment]
https://github.com/hrzntal/horizon/pull/391 Allows wrench acting implements to fix the bone issues
I checked the other wound surgeries and:
 - Burn dressing can be done with wirecutters
 - Fixing punctures can be done tools too
 
 Which leaves with no more emergent surgical issues not having ghetto ways to fix them, that I know of?
 Or is there anything else you'd like changed regarding ghetto surgery stuff?

**Comment by Azarak** [comment]
Ripping clothes for cloth for improvised gauze maybe? Is that a thing?

**Comment by atakiya** [comment]
> Ripping clothes for cloth for improvised gauze maybe? Is that a thing?

If it isn't would be pretty neat. I really don't see why we shouldn't be able to rip clothes into cloth.
There might some balance issues due to the abundance of clothing.. but I think in the future we'll probably have some made out of nylon or other materials that arent cloth (think medical/chemical or engineering clothing)

**Comment by atakiya** [comment]
In regards to this issue I'm also thinking about making ghetto surgery a little bit more risky.
Recently i was able to completely replace someone's limbs (two legs, one arm) just with a toolbelt, two times with barely any downsides.

Now with infections, this could get very nasty, which is something I think we'd probably get later down the roads. (hopefully).
But if theres anything else we could quickly add on, or so, then yeah.
Maybe the success chance should just be a SLIGHT bit worse? Or maybe it always does a bit of damage while also fixing it?
So like, you do success in the operation, but it causes maybe brute damage with each step.

Fixing bruises/burn damage should also not be a thing with ghetto tools I think. It completely nullifies the damages that screwing up currently does, and the above idea too.

**Comment by Owai-Seek** [comment]
Currently the only improvised cloth you can get is from cutting bedsheets with a sharp object.

For clothing, I'd recommend it being an action that damages the clothing rather than destroying it, like tearing off a sleeve. (Which means you can repair it later, if you want.) It would be more RP friendly (and less greif-baity) that way.

Doing damage for using ghetto tools does sound like a good idea, but if it's on each step, it'd probably have to be on the low, as things would add up quickly. The exception being tend wounds, which should barely work, if at all.

Alternatively (or in addition), we could introduce the need for anesthetics, Require people to be boozed/numbed up for surgeries.

**Comment by atakiya** [comment]
> For clothing, I'd recommend it being an action that damages the clothing rather than destroying it, like tearing off a sleeve. (Which means you can repair it later, if you want.) It would be more RP friendly (and less greif-baity) that way.

While I agree, this would mean more functional stuff on EVERY clothing article. Clothes aren't exactly uncommon, so completely ripping them apart isn't too much of an issue. Not like you should be doing it as often enough to actually do a dent in the clothing amount either.

> Alternatively (or in addition), we could introduce the need for anesthetics,

This. Feedback and fluff messages for pain is something that will take care of that later on. Out of scope for this issue though.

**Comment by atakiya** [comment]
Clothing ripping covered in #811 
Ghetto surgery was implemented/fullfilled by #391 
Pain/infection etc is out of scope, and should be covered by another issue.
