### ISSUE TITLE
Feature Request: Towel Port

### ISSUE THREAD

**Issue by Owai-Seek** [hrzntal/horizon#451]
## About The Feature Request

Towels are a fun an interactive way to get some shower RP. I'll save my rant on showers for another time though. What we're -missing- are the towels.

I originally saw them on Citadel, but apparently the sprites are from Aurora? Should be able to crawl through the Citadel PRs to find it.

Basically, just, a wearable towel for head/chest/belt slots, that you can possibly lay out on the floor? Additional functionalities were like... acting as a rag or weapon, but I'd rather the towel snapping be "flavor" damage, rather than real damage.

Also, Zephyr told me to make a request.

## Why It's Good For The Game

Shower RP is fun, and I miss it. Would also be good for sauna RP, beach RP, picnics, ect.

**Comment by ZephyrTFA** [comment]
@atakiya assign this to me so I don't forget about this ty

**Comment by atakiya** [comment]
Implemented by #620
