### ISSUE TITLE
Mail system seems to ONLY send spam mail now. No player addressed mail.

### ISSUE THREAD

**Issue by Owai-Seek** [hrzntal/horizon#474]
## Round ID:

116

## Reproduction:

Sent the shuttle out, and brought it back in multiple times over a two hour period. There was nothing but spam mail. May have noticed it on the previous shift too, but I just thought it was being wonky.

**Comment by atakiya** [comment]
Can confirm.

**Comment by Owai-Seek** [comment]
This issue may be resolved, I think, but there's a new one I might make a new issue about. Mail doesn't spawn with any color coding anymore, which may be a fault of the job refactoring that was done.
