### ISSUE TITLE
Bring recent HFR updates to Horizon.

### ISSUE THREAD

**Issue by DimaPeep** [hrzntal/horizon#498]
## About The Feature Request

This is a request to gather recent changes to the HFR that make it easier to run and do a few QC updates. Mainly from TG and SR.
 

The most important part of these updates were the fuel and cooling rebalancing. The HFR can only contain certain amounts of gases in both the fuel input and moderator input before it leaks and late ruptures. Prevents excessive internal gases in case of a full delam.

The changes allow for scaling of cooling through player input rather than one consistent level of cooling.

Other changes are quality control revolving around fuel issues, how the HFR is assembled and more.

Recent changes to the HFR provide an easier learning experience and safer experience for the station as a whole. Preventing larger version of this from happening most often:
![image](https://user-images.githubusercontent.com/89415431/130515098-a8c62ee6-1385-4428-a4b1-e5c18ee18beb.png)

And instead resulting in more manageable things such as this: 
![image](https://user-images.githubusercontent.com/89415431/130515127-8e902da2-b2fd-4a46-984b-c4f4f9824ba6.png)

Or this: 
![image](https://user-images.githubusercontent.com/89415431/130515295-8032c079-0963-48a2-ac65-6313cc4f0b2d.png)

When folks decide to be irresponsible with the machine. While full delams are still possible, they are much less destructive and possible to recover from.

## Why It's Good For The Game

In general, more options to control the HFR, safer HFR, safer station. These changes make the HFR somewhat less confusing to assemble and setup.

Less destruction delams. Less likely to fully delam under learning hands. Better options for cooling meaning easier control over the HFR. 

General QC making life easier for whoever is setting up and running the HFR.

**Comment by atakiya** [comment]
HFR is to be deprecated on this codebase. Closing.

**Comment by Azarak** [comment]
Make an issue to deprecate it and replace it?
