### ISSUE TITLE
Can RCD supposedly Reinforced concrete walls used in ruin mapping.

### ISSUE THREAD

**Issue by CypressBz** [hrzntal/horizon#656]

**Comment by atakiya** [comment]
Uh.. more information?

**Comment by MissFox0810** [comment]
![WhatAreYouTalkingAboutHuhGIF](https://user-images.githubusercontent.com/4310446/149380950-7924895f-2e35-4504-9af5-c7120ed8c2ad.gif)

**Comment by CypressBz** [comment]
EHEM 
/turf/closed/wall/concrete
Prior to Azarak's wall rework, was "Reinforced" like RWalls and couldn't be RCD'd It now can.
