### ISSUE TITLE
Mismatching pipes between distro and security LS on Pubby

### ISSUE THREAD

**Issue by atakiya** [hrzntal/horizon#661]
## About
Map: Pubby Station (revision 505e2f3d9f698b3048c65c886cff84d356a9363f )
Life support distribution piping is broken between the Security department and the rest of the station.
Cause is pipe colour mismatch.

**Comment by atakiya** [comment]
Uuuuh, pubby.

**Comment by MissFox0810** [comment]
For foxes future refarance its pubby
