### ISSUE TITLE
Plasma Wall does not count at Plasma wall for Experments

### ISSUE THREAD

**Issue by MissFox0810** [hrzntal/horizon#696]
### Description of the Issue

RnD research for this round required a plasma wall.
But both a constructed, and spawned plasma wall does not work. It does not match.
<img width="484" alt="image" src="https://user-images.githubusercontent.com/4310446/149642332-3963413e-05bb-4d9f-96b0-c3f9d54b7ba5.png">

**Comment by drizzlemutt** [comment]
Looking into this. 

This seems to be the case with all mineral_walls, as I tested it with the others. These scans seem to require a defined custom_materials value within material_walls that is currently missing, to tell the scanner that the wall has the materials its looking for.

Adding said value seems to remedy this issue, no idea if this causes issues else where.

**Comment by drizzlemutt** [comment]
This value is present within obj/structure/chair, obj/structure/toilet, and obj/structure/table, which allows for them to be scanned without issue.
