### ISSUE TITLE
Gravity generator keeps turning off repeatedly

### ISSUE THREAD

**Issue by atakiya** [hrzntal/horizon#703]
### Round ID / Commit SHA

505e2f3d9f698b3048c65c886cff84d356a9363f

### Description of the Issue

The gravity generator will keep turning itself off repeatedly when power is lost.
Currently this was only observed on the power failure event.

![image](https://user-images.githubusercontent.com/6952402/149717713-6d845a8b-ccb3-40bb-8889-064936d29c58.png)

This also causes excessive shaking to clients which isn't very UX friendly.

**Comment by MissFox0810** [comment]
I think this might be a pubby thing. Ill check the APC for that area.

**Comment by atakiya** [comment]
This is still an issue after #712 / 5da2f32
