### ISSUE TITLE
Smooth Plated Catwalk Using Two to Place

### ISSUE THREAD

**Issue by AsaiasWolffe** [hrzntal/horizon#735]
### Description of the Issue

When placing the smooth plated catwalk tile it uses two instead of one.

![image](https://user-images.githubusercontent.com/59212063/151065002-5f520dac-bc73-406d-bf4c-56f3aae3f2eb.png)
Prior to placing one down
![image](https://user-images.githubusercontent.com/59212063/151065060-73c7ca66-f956-4cf7-a5e6-02e7f6c7b262.png)
Post placing one down

### Reproduction Steps

Build them with rods and place them

**Comment by AsaiasWolffe** [comment]
In addition to this it seems it wont hide layer 5
![image](https://user-images.githubusercontent.com/59212063/151090956-0a0a90cf-6b51-43d0-9897-a4424d0d76b4.png)

**Comment by Azarak** [comment]
Intentional to preserve matter after you place them down on a lattice
