### ISSUE TITLE
Add a third planet spawn to station maps.

### ISSUE THREAD

**Issue by CypressBz** [hrzntal/horizon#792]
### Type of Request

Addition

### About the Request

Add a third planetary spawn besides lavaland and the forced habitable one, could even force it to be something that's not on the habitable planet pool.

Though I still feel like lava planet shouldn't generate until we get rid of the forced lavaland planet.

### Why should this Idea be considered

gives the few weird planets we have some space to shine, more challenge beyond "mega fauna and fire" for people to play around with. gives space to start moving content from lavaland onto other planets.

**Comment by atakiya** [comment]
Funny, didn't even know this issue existed.

Implemented by #1090
