### ISSUE TITLE
Borg modular interface tgui crash.

### ISSUE THREAD

**Issue by CypressBz** [hrzntal/horizon#798]
### Round ID / Commit SHA

253

### Client Version

514.1578

### Description of the Issue

Opening the hardware manager sometimes, as well as IRC admin mode button crashes TGUI to bluescreen.

kind of inconsistent.

Possibly removal of admin button outright, would also go further to make the irc chat a better PDA analogue for borgs.
Alternatively, take away AI's NToS Admin access?

### Reproduction Steps

1. open IRC on modular interface.
2. touch effected stuff
2a. press admin button.
2b. open hardware manager
3. tgui bluescreen.
4. cry as you need reset to fix.

**Comment by MissFox0810** [comment]
Confirmed. Managed to replcated this every time. its directly related to the Admin interface on IRC. moving to any screen away from the IRC screen after clicking that causes the crash
