### ISSUE TITLE
Replace Borg's Modular Interface network card with an advanced network card.

### ISSUE THREAD

**Issue by CypressBz** [hrzntal/horizon#799]
### Type of Request

Change

### About the Request

Seeing as how we can't currently extend NTos access, or upgrade borg's modular interface, replacing the normal network card in the Borg's modular interface with the advanced upgrade would allow them to connect across Z-levels.

### Why should this Idea be considered

Borgs have binary across Z levels already,
There's no way to upgrade the borg's to have this in shift.

**Comment by atakiya** [comment]
Closing in favor of #800
