### ISSUE TITLE
EVA tumbling even with gravboots enabled

### ISSUE THREAD

**Issue by Dr-0range** [hrzntal/horizon#85]
Reporting client version: 513.1536

## Round ID:
38

## Testmerges:
- [[TM ONLY] 24 Add Heaters to Air alarms](https://github.com/hrzntal/horizon/pull/61)
- [Initial support/addition of Teshari species](https://github.com/hrzntal/horizon/pull/46)
- [Adds SQL Logging - by missfoxie](https://github.com/hrzntal/horizon/pull/8)
- [Attribute & Skill system](https://github.com/hrzntal/horizon/pull/78)

## Reproduction:
@Azarak is aware of the bug, just reporting to keep a clear view on it!

**Comment by Azarak** [comment]
https://github.com/hrzntal/horizon/pull/78/commits/5facdc3b2401e586abd1f8fd5c14ea964b5d7dc8 Should fix it

**Comment by atakiya** [comment]
Reopen if still an issue, closing as fixed/stale.
