### ISSUE TITLE
Removing the fly TF from Teleporters

### ISSUE THREAD

**Issue by CypressBz** [hrzntal/horizon#909]
### About the Request

Lame to play, lame to roleplay, lame to deal with, Removal of the code here in [teleporter.dm](https://github.com/hrzntal/horizon/blob/a34db6247c7026d08f7ada6de192d0598a0290a7/code/game/machinery/teleporter.dm#L78)

### Why should this Idea be considered

No one likes it, it's really hard to roleplay without turning your round into a horror round, and there's no cure.

**Comment by atakiya** [comment]
Reclassifying this as a severe bug (haha)

**Comment by CypressBz** [comment]
Gottem 👏
